// Options the user could type in
const prompts = [
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may i know your name",
    "what is your name",
    "what call yourself"
  ],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "good bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no","not sure","maybe","no thanks"],
  [""],
  ["haha","ha","lol","hehe","funny","joke"]
]

// Possible responses, in corresponding order

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!","Howdy"],
  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["The one true God, JavaScript"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Sushi", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok","I understand","What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!","Good one!"]
]

// Random for any other user input

const florentin = [
"… Ouh, Ha Ha Ha Ha",
"…18 ist größer als 30.",
"… aber ich sag mal: Früher war Silvester schon geil, weil, ich war ‘n riesiger Böllerfan…",
"… an Silv… Silvester vorstellen? Was machst du zu Sil…Das ist meine zweite Frage an Stefan Tittze.",
"… die Silvesterraketen reinfeuerst…",
"… die wir als hässliche Leute als schön empfinden, glaubst du, es gibt Leute, die die noch schöner finden?",
"… die zwölfjährigen Kinder von nebenan… die zwölfjährigen Kinder von nebenan sprengen das schon in die Luft, also, man kann eigentlich auf die Straße hauen, was man will. Und am nächsten Tag wird eh aufgeräumt!",
"… selbstständig dort hin galoppieren, wo du hin willst? Die musst du gar nicht führen!",
"… und irgendwann… und irgendwann die E… [lacht auf] die Eltern anfangen zu fliehen, weil…was sollen sie denn machen? Sie können… Ha ha ha!",
"… und manchmal auch mal schludrig sein und sagen: Scheiß doch jetzt auf diesen Drecksbauern, der seine Hühner verloren hat, egal.",
"… uns ja auch ein Bisschen abheben. Wir wollen uns ja auch ein Bisschen ABHEBEN!",
"… was ist dein größter Traum?",
"…der Hund dich zieht automatisch schon in die Reihenfolge. Und da dacht ich mir: Wär’s nicht eigentlich die beste Idee, statt Blindenhunden Blindenpferde, auf die du dich einfach draufsetzt, und die au…aut…automatisch…",
"…Glaube nicht, was…äh… der Fall ist… mit…Das Problem an rappen ist, dass es so schnell ist. Ich kann’s einfach nicht. Nein, äh, um mal…",
"…ich ha… ich hab dich grade gefragt, was dein größter Wunsch ist, und du hast gesagt: Ich möchte in Relation zu anderen besser aussehn, da muss doch irgendwo ein kleines…",
"…Leute hassen Streber. Nein, ich will…du, du möchtest ja…",
"…Minderwertigkeitskomplexchen irgendwo versteckt sein, oder? Das glaub ich doch schon.",
"…na gut, entweder bricht das Universum hier grad zusammen, …",
"…oder es stimmt nicht. Ich sag mal… Nein, du möchtest ja auch erfolgreich und interessant werden so wie ich, und da kann ich dir nur eine Sache raten: vermeide Dinge, die alle Leute hassen. Was alle Leute hassen, sind Streber, und sind Leute, die gut aussehn.",
"…Sag ich mal als Lifestyle-podcast, messen wir uns mit einem Wissenschafts- und Verschwörungspodcast, unser Traum ist es…",
"…Sonnenbrille gekauft und ich werd’s auch glaub ich nicht tun, weil ich find, ‘ne Sonnenbrille ist ein komplett überflüssiges Acessoire.",
"…Tittze, Tittze…",
"…und auf statt offen…",
"…und ich bin ja … ähm… Ich hab das immer in der Nähe von… von Österreich gefeiert, ganz im südlichen Ende von Deutschland, und dann sind wir nach Österreich gefahren und haben uns Ösi-Böller geholt, die sehr billig sind und sehr stark, und daraus haben wir dann immer…äh… Bomben gebaut, und was wir auch gemacht haben: Wir haben so Gewehre gebaut. Wir haben uns so ‘ne Stahlrohr genommen und das an einer Seite zugehämmert und dann da irgendwie ‘n Böller reingetan und ne Murmel und dann damit geschossen einfach. Das funktioniert sehr gut tatsächlich. Und das macht echt Spaß…",
"…weiter verfolgen, und ich mag es auch einfach, objektive Beurteilungen zu bekommen, dass man was drauf hat. Schönster Mann der Welt wär nichts für mich, wirklich, wär nichts für mich…",
"…Wir da… [geht näher ans Mikrofon] Wir da draußen, wir können’s auch schaffen, ein noch erfolgreicheren Podcast zu starten, als Podcast U.F.O. [wieder normal] Vor allem, ist auch so gut, dass wir uns als,…",
"…zu retten, dem armen Bauern auf dem Feld muss auch geholfen werden.",
"[beginnt zu beatboxen] Ha ha ha! Ich find, du machst das richtig gut…",
"Andere Leute haben gesagt, dass ich gut bin",
"… der dich…der dich automatisch…der dich automatisch führt und…und zieht?!. Dass du wie so’n Streitwagen…",
"[äfft Leute von Podcast U.F.O nach]… Der hat 30.000 Likes. Wir sind so’n toller Podcast. Wir haben ganz tolle Folgen und tolle Inhalte. Wir haben so viel nenenene… Die gehen mir jetzt schon so auf ‘n Sack, diese Penner, und ich sag’s euch, Freunde: Wir…Das ist auch immer so schlecht, Verbrüderung mit den Zuhörern, ne? …Wir da draußen…",
"[atmet geräuschvoll aus] Bring it, bring it.",
"[imitiert Windrauschen]",
"Ha ha ha! Wenn’s schon so anfängt…",
"Ah, okay…",
"Aha… nee, ist okay.",
"Das ist ‘n Trick zum…äh… zum Nachmachen. Nee, ohne Witz, ist kein Witz! Und vor allem: Auch ohne Murmel hast du so’n gewissen Rückschlag , der einfach total cool is als Kind…äh…da so ‘ne Art…äh… Muskete oder…äh…Gewehr zu haben, und das is wirklich total geil, und da haben wir… es is…äh… wirklich total cool, und…äh… was total Spaß macht, ist: Man kauft sich ganz viele Raketen und versucht, an Silvester, wenn dann irgendwie die ganzen Eltern mit ihren Kindern auf den Hügel in der Nachbarschaft gehen, und…",
"Die antworten werden auch immer skandinavischer: Ney",
"Du kannst einfach deine…",
"Hast du aber auch grade gemacht. Hast du auch grade gemacht.",
"Humoristisch gesehen häng ich schon an den Seiln. Ich bin der schlechteste Schauspieler, wolltest du grad sagen? Heißt das, ich werd nie ‘n Oscar gewinnen?",
"Ja.",
"Ja…",
"Ja…",
"Ja… Ferd, du sagst auch Ferd.",
"Laptop is kein Mobile Device!",
"Lass den…",
"Richtig!",
"Silvester ist objektiv etwas Gutes.",
"Verstehe.",
"[lacht, dann wieder mitleiderregend] …indem ihr diesen Podcast shared und liked und auf Twitter allen euren Freunden sch… und Eltern schreibt: Hört diesen Podcast. [Wieder normal] Apropos Eltern: Wie muss man sich eigentlich Stefan Tittze…",
"Ha ha ha!",
"Ha ha ha!",
"Ha ha ha!",
"Ha ha ha!",
"Ha ha ha! …Wir schaun uns da Silvester an, wir schaun uns das Feuerwerk an und ballern da hoch, und du aus 30 Meter Entfernung in dem Busch mit deinen Freunden AUF diesen Hügel in die Menschenmenge der Feiernden…",
"Ha ha ha! Aha, …",
"Ha ha ha! Also dass alle anderen Menschen außer dir so 20 Kilo zunehmen.",
"Ha ha ha! Drrr… Was war das für’n Geräusch? Drrr…drrr…",
"Ha ha ha! Genau, jetzt mal Spaß beiseite.",
"Ha ha ha! Genau…",
"Ha ha ha! Haaa…Sehr gut!",
"Ha ha ha! Ist das deine Meinung zu Silvester, Es ist nicht schlecht?",
"Ha ha ha! Ja, absolut!",
"Ha ha ha! Nein, aber, ich…du bist so ‘n richtiger Streber, und…",
"Ha ha ha! Nein… tut es nicht.",
"Ha ha ha! Oder nicht explodieren. Einfach mal n‘ Altmüll… Ha ha ha!",
"Ha ha ha! Vor allem Ich… Ich liebe es, dass du deine…deine…dein…Glauben-Sätze formulierst zu Fakten, ja? Ich glaube, dass das chinesische verwandt ist mit dem Deutschen, einfach glauben, Sachen die einfach nicht stimmen: Ich glaube,…",
"[lauter werdend] Nein, nein, nein, nein! Wenn… wenn sich mal Campino einsetzt für die armen, verhungernden Kinder in Afrika, dann bist du so jemand, der dann ankommt und sagt: Nein, die wollen sich doch nur profilieren, nenenenene…. Du bist einfach immer dagegen, und das mögen Leute auch nicht und… Nein, das mögen nämlich Leute viel zu sehr, Leute die dagegen sind, und das ist billig, das ist Anbiederung an die Zuschauerschaft, das find ich zum kotzen.",
"[mit Ansagerstimme] 20 Fragen an Stefan Tittze, Tittze, …",
"[mitleiderregend] Und ihr könnt mir diesen Traum ein Stück weit erfüllen, indem…",
"[rappt] Salz, Pfeffer, Pfeffer, Salz, das Podcast UFO hebt ab mit seinem Traktorstrahl…",
"[räuspert sich] Ich weiß nicht, (Phillip?), du…äh…du gefällst mir grad nicht.",
"Nummerell. Ha ha ha! Ist das der Bruder von Karl…Karl Da… von Rudi Carrell?",
"[lacht auf] Waren alle schon weg!",
"Ha ha ha! Die… Da wirst du sofort skeptisch:  Warum ist der so selbstzufrieden ?",
"Aber auf der andern Seite, Ja…",
"Der Körper hat ‘ne eingebaute Sonnenbrille!",
"Frage drei: Wo kommst du her?",
"Genau, hüpfend und in den Funken und zwischen den Blutfetzen.",
"Ist eigentlich die Regel, ja…",
"Ja gut, vielen Dank, …vielen Dank, Herr Besserwisser.",
"Ja, aber es muss ja nicht unbedingt lustig sein.",
"Muss man das machen?",
"Na, dann gibt’s dann halt Extra-DMs.",
"Schau mal! Ich hab dich grade gefragt, was dein größter Wunsch ist…",
"Und könntest nicht einfach du schöner werden?",
"Vor allem: Ich wusste auch grade nicht, was ich sagen w…sollte, deswegen hab ich an…angefangen mit Die Sache ist ja Die. Kommen wir zurück zu der ersten Frage an Stefan Tittze,…",
"Was…was glaubst du, sagt Brad Pitt: Ich würde gern so aussehn wie…. Glaubst du, es gibt jemanden? Oder s…so die Leute, die wir…",
"A… Ha Ha Ha Ha Ha Ha! Falls ihr übrigens an unsrer tollen Sendung teilnehmen wollt, könnt ihr das tun über Facebook, äh… Das Podcast UFO, oder über Twitter, Hashtag UFO, äh… schreibt dort einfach…",
"Aber auf der andern Seite macht man sich auch rar. Ich mag ja die Leute, die in ‘ner…in ‘ner Gruppenkonversation schon ewig lang drin sind, und erst so nach zwei Wochen überhaupt erst mal antworten. Da denkt man sich: Ouuh…Okay…Ouh, ja, Uiuiui…",
"Aber dafür haben wir doch unsere Traktorstrahlen, denn wir sind ein UFO.",
"Aber du kannst auch einfach deine Augen zu machen!",
"Aber meinst du… meinst du, das sa… würden die dann sagen?",
"Aber warte mal, das ist eigentlich gar keine so dumme Idee. Man haut … an Silvester einfach seinen ganzen Müll, sein Altglass, auf die Straßen, weil es wird sowieso alles sauber gemacht, wegen den Böllern.",
"Äh… Ich glaub…Moment, ich muss ich jetzt nachgucken…",
"Aha, warum nicht?",
"Ähm, ja, wär zumindest sehr cool. Also, ich sag mal so, der…der Weg der Schauspielerei find ich sehr interessant und sehr spannend und würd ich auch gern…",
"Ähm, nein, die Sache ist ja die, ähm…",
"Alter, wenn… wenn du deine Brille noch aufsetzt und gut aussiehst, dann hast du’n riesiges Problem.",
"Dann fangen die Leute automatisch an zu lachen, ja.",
"Das ist dein großer Traum.",
"Das macht dich… macht dich real.",
"Doch, natürlich!",
"Du willst immer alle Aufträge erfüllen. Ich wette, so in Videospielen bist du so jemand der alle Sidequests macht, so: [Stefan imitierend] Nein, es ist nicht nur wichtig, die Prinzessin…",
"Einfach mal schön auf die Straße entleeren, und dann… ich mein…",
"Es gibt auch ‘n anderen Podcast, der heißt Podcast U.F.O aus Amerika,…",
"Genau, aber es ist so gut, die Vorstellung: [imitiert unschuldige Opfer] So, wir gehen jetzt da hin… Aah, wir gehen doch direkt … [imitiert Explosionen] Aah, wir gehen wieder, wah, tschüss, bis morgen. Genial.",
"Glaubst du wirklich, dass Brad Pitt sagt:  Ich bin der Schönste Mann der Welt! ?",
"Ha Ha Ha Ha Haa! [räuspert sich] Da war…das…war jetzt noch n’ Bisschen der Raucherhusten mit drin.",
"Halt die F… Das hätte niemand gemerkt, du Depp!",
"Huff, Huiuiuiuiui, Ich, Ha ha ha! ich häng in den Seiln. Humoristisch…",
"Humoristisch häng ich in den Seiln. Okay, wir fangen mal an. Humoristisch häng ich hei… häng ich schon an den Seiln…",
"Ich hab mir jetzt tatsächlich in meinem Leben noch nie ‘ne…",
"Ich komm aus München, ja.",
"Ich mag ja Silvester. Ich find das ja ganz toll, sich immer zu treffen mit alten Leuten, weil, ich w… wohn ja mittlerweile außerhalb meines alten Freundeskreises und dann mal wieder alle zu sehn und so toll und zu sagen: Hier und da…",
"Ich sag Pferd. Ich versuch es zumindest.",
"Ist auch ein Traum, den ich nicht wirklich aktiv verfolge, bin ich ganz ehrlich.",
"Ja",
"Ja, auf ‘ne gewisse Art schon, aber um nochmal zurückzukommen auf meinen größten Traum:…",
"Ja, ich komm aus München. Ich hab ‘ne Zeit lang in München gelebt, bin aber etwas außerhalb von München geboren worden, so.",
"Ja! Du musst es erklären.",
"Ja.",
"Ja.",
"Kann gut sein, dass die mal 2008 oder so…",
"Mein größter Traum ist es, einmal einen Oscar zu gewinnen.",
"Mein größter Traum wäre es, [mitleiderregend] einen erfolgreichen Podcast zu haben.",
"Moment ! Objektiv gesehen ist es natürlich nicht objektiv, aber in ‘ner subjektiven Hinsicht kannst du zumindest sagen:  Hä, du hältst dich für ‘n guten Schauspieler? Ich hab immerhin ‘n fucking Oscar gewonnen!. Da kann man nicht mit argumentieren. Dass du natürlich nicht notwendigerweise der beste Schauspieler in dieser Kategorie warst zu dem Jahr, das ist ja klar, aber hast zumindest ‘n objektiven Anker, dass du sagen kannst: Andere Leute… Du hast ei…ei… ein Intersubjektiv nennen wir es mal.",
"Naaaja…",
"Ne…Nein! Nein, nein, nein, nicht… nein, es ist… Moment Mal!",
"Nee, das ist…Das ist okay, das ist dynamisch, das ist jugendlich, frisch, spritzig, wir wollen …",
"Nee, du sagst Ferd.",
"Nein, ich glaube…",
"Nein, ich mag das nicht, das… du bist so Lavira. Du bist so’n: Alle mögen X, also sag ich, das X nicht gut ist. Du bist so’n richtiger Facebook User. Du bist so’n Typ, der schreibt…",
"Nein, wir haben sicherlich keinen Kommentar bekommen.",
"Nein! Nein, natürlich nicht!",
"Nein! Zum Glück nicht.",
"Ney. Ha ha ha! Ney.",
"Ouuuuh…",
"PDM. Pferde-DM.",
"Populismus hat nicht umsonst die Worte I L U drin: I lose you.",
"Silvester ist…",
"Stefan, was ist dein größter Traum?",
"Und Besserwisser.",
"Und deswegen, weil es einfach zu subjektiv ist, Weißde? Du bist der schönste Mann der Fr…äh…Du bist der schön… die Schönste Frau der Welt, dann kommt der reichste Mann der Welt zu dir und sagt: Moment mal, wir haben hier ein paar Zahlen, die sagen ganz eiskalt, ich bin der reichste Mann der Welt. Was hast du denn?. [imitiert verschiedene Personen] Ja, Nee, ich find den Schöner, Ich find meine Freundin Schöner, bla, bla, bla. Weißde, das ist sowieso, es… das ist halt auch ein Problem.",
"Und du sagst, subjektiv ist es nicht gut.",
"Vor allem letztens hab ich nen Hund gesehn, der… nen Blindenhund oder nen Behindertenhund oder sowas, und der hat einer Frau assistiert, die im Rollstuhl saß, und da dacht ich mir: Ist das eigentlich so auch so’n Angebot von solchen Hundeverkäufern, die ‘n Hund anbieten,…",
"War das schon die erste Frage an mich?",
"Weißt du, das… das hass ich an dir, deswegen find ich, dass du so ein richtig widerliches (wiedriches) Arschloch bist, weil du so ein Overarchiever bist. Du willst immer alle Häkchen haben.",
]


const stefan = [
"… am nächsten Tag. Wird das bei euch sauber gemacht? Bei mir… bei uns ist nämlich… äh… Pflicht, da wo ich herkomme, ist nämlich die Pflicht… hier übrigens Fra…",
"… die beste Schauspielerin des Universums, so. Hat noch keinen Oscar bekommen, oder lieg ich da falsch?",
"… ein Schönheitsideal wird, in dieser Welt. Und das…",
"… hat man mit dem Pferd dann ‘n Problem.",
"… ich find’s auch gar nicht so schlecht, nicht dünn, nicht dick zu sein, so’n Mittelding zu sein ist nicht schlecht, aber wenn dass das Schönheitsideal wär, wär halt perfekt. Das wär für alle am Einfachsten. Und dass Leute dann sagen – auch Stars, wo man jetzt sa…denkt: Oh, Fuck, ich würd gern so aussehn – dass die sagen:  Fuck, ich würd gern so aussehn wie Stefan.",
"… ich… das ist auch so’n Ding von mir, ich werde einfach schweigen, wenn mir nichts einfällt… Äh, mein größter Traum ist, dass alle Menschen… Ähm…",
"… irgendein Mobile Device… [reagierend] Aus…aber nur aus, um zu kontern.",
"… und Besserwisser.",
"… und so sind ein… Mei… Glaubst du, UV-Strahlen sind ‘n Ding was…ähm… Sonnenbrillenhersteller erf…äh…erfunden haben, ein Mythos?",
"… was natürlich sehr clever ist, weil das das vorherige Gesagte so aussehen lässt, als ob es unglaublich lustig gewesen wäre. Ja, vor allem, die Leute haben ja ein wahnsinnig schlechtes Gewissen, das heißt sobald du sagst, nach ‘ner langweiligen Rede: Spaß beiseite, denken: Ach, das war alles ‘n Gag?...",
"… Weil die… Nee, weil die das Gespräch schon wieder in ‘ner ganz anderen Richtung ist grad.",
"…als Blinder… aber mit ‘nem Pferd…",
"…außer…außer mir selbst, außer mir selbst, dass alle Menschen … Ähm … dicker sind.",
"…das ist natürlich ganz… ganz verbreitet eigentlich, und dann, ähm…",
"…das Schwarzpulver in ‘n großen… Ich hab so’n, so’n, so’n Teppich aus Taschentüchern gebastelt, hab darin dann ‘n Riesenhaufen von diesem Zeug gehabt…",
"…ich hab mal ‘ne Studie durchgeführt, dass man zu spät zu Partys kommen soll,…",
"…ich hab nämlich mal dieses,…",
"…mehr. Ab jetzt versprech ich mich nicht mehr. Ähm…",
"…scheiße aussehn, Leuten durchgehn lassen, wenn sie wie statt als benutzen,  Einzigste sagen…",
"…und Zumindestens…",
"…und dann kam ich zu spät! Und du musst nämlich genau den Punkt abwischen, äh, ab…ab…abstecken… Ha ha ha!",
"…wollt ich es dann mal einführn, zu spät zu Partys zu kommen, um cool zu sein,…",
"Super, der muss…hab ich nicht verstanden…",
"… auf Nora Tschirner.",
"…bestreiten.",
"…Objektiv…Meistens… Die Meistens nicht explodieren. Ha ha ha!",
"…Oder blind.",
"Ha ha ha!",
"Ha ha ha! Auf die Hügel…",
"Ha ha ha! Du hast nichts gedrückt!",
"Ha ha ha! Ist uns erst aufgefallen… Ja, ist uns erst aufgefallen, als wir schon… als wir schon drei Euro… mit drei Euro einen Beitrag von uns beworben haben.",
"Aaaah… Ha ha ha!",
"Aber…",
"Da gewinnen doch auch… Da sagen doch auch alle… Leonardo Di Caprio ist der beste Schauspieler der Welt und hat noch nie einen Oscar bekommen!",
"Das ist ‘ne gute Frage.",
"Das wär genial!",
"Feierst du zu Hause?",
"Ich auch! War ich auch, zugegeben.",
"Ich glaub nicht, dass…",
"Ich hab nicht mit meinem Aussehn…ich hab nicht mit meinem Aussehn… ich hab nicht mit meinem Aussehn abgeschlossen!",
"Inklusion.",
"Ja, weil ich mir dann denke…",
"Ja.",
"Ja.",
"Kuck mal kurz nach!",
"Manchmal leuchten sie auch…",
"Nehmen wir schon auf eigentlich?",
"Nummerativ!",
"Ouh, ouh, ouh…",
"Tipp. Unser Freizeittipp.",
"Titze",
"Titze!",
"Was mich…was m…",
"Wir sind jetzt schon in ‘ner… Wir sind… Nehmen wir eigentlich schon auf?",
"… der muss unglaublich schlau gewesen sein.Ja. Ich f…Wir reden immer durcheinander, glaub ich das Gefühl.",
"[imitiert Grille] Drrr…drrr… Das war…",
"[lachend] Och Gott…",
"Ha ha ha!",
"Ha ha ha! Aus der Stauschau! Weil da immer Stau ist, weil da die A1 die A2 trifft. Ist ‘ne Bildungslücke, die größten beiden Autobahnen Deutschlands treffen sich… größten weiß ich nicht, aber zumindest die 1 und die 2 halt. Die… äh… nummerell wichtigsten Autobahnen Deutschlands treffen sich an diesem Punkt, und genau da ist nämlich Kamen…",
"Ha ha ha! Hab ich…",
"Ha ha ha! Ich glaub nämlich auch, dass so… so skandinavische Sprachen irgendwie von Deutsch abstammen, Deutsche, die sehr schluderig reden, reden irgendwann dänisch, glaube ich.",
"[leiser werdend] Titze, Titze",
"… aber die Kinder es cool finden, und die Kinder so, hüpfend und…und drehen sich…",
"…für Leute, die im Rollstuhl sitzen oder blind sind…oder einfach nur blöd.",
"Aber Leute lieben mich!",
"Aber nicht mit mir! Aber… Solange ich in diesem Raum mit dir sitze, wird es nicht passieren!",
"Bitte macht nicht den Fehler bei Facebook, nur Podcast UFO einzugeben…",
"Das ist auch ‘n Trick zum Nachmachen, Ne? Bitte nachmachen!",
"Das stimmt ja gar nicht!",
"Du musst ein gutes assoziatives Gedächtnis haben.",
"Es is nicht weit weg von Impro-Comedy, Rap, Freestyle. Du musst ja auch schnell…",
"Ich find aber, wir sind auch sowas wie ‘n Verschwörungspodcast.",
"Ist nicht objektiv genug?",
"Ja, weil man dann nämlich in der Hauptstory nämlich schon mehr hat, dann hat man halt schon mehr Taler gesammelt, man hat schon mehr Credits gesammelt… Ich find’s gut, dass du jetzt auch nicht aufs Handy kuckst oder so…",
"Und es ist nicht perfekt…Es macht uns sympathisch, glaub ich.",
"[untermalt rappen mit Geräuschen]",
"Aber Spaß beiseite!",
"Achso.",
"Ähm… Ich glaube, dass Brad Pitt, ähm, um auf die Frage nochmal zu antworten, ähm, keinen hat.",
"Ähm… Was ist denn dein größter Traum?",
"Alle laufen mit Luftschlangen rum und Partyhüten und um 12 müssen… wenn man eine Minute zu spät ist, dann fangen die Nachbarn nämlich schon an, das ist alles… nur halb so lustig, und ähm… man muss gut drauf sein, man muss um 12 Uhr was trinken, anstoßen. Das ist ein Datum, was dir zu jeder Uhrzeit was vorschreibt. Es läuft auf allen Sendern nur  Dinner for One, danach läuft auf allen Sendern nur Ein Herz und eine Seele… S… Herausragender Sketch!",
"Also, das heißt, du musst n‘ Bisschen schneller…",
"Also, wir sind das… ich find immer noch, wir müssen erklären, wer wir sind. Wir sind das „Podcast UFO“…",
"Also: man muss…",
"Auch noch reinspringen und versuchen, die Dinger zu fangen…",
"Dafür redest du aber schön.",
"Das ist ‘ne gute…",
"Das ist ein Datrum, das di… ein Datum, was dir vorschreibt, gut drauf sein zu müssen, finde ich.",
"Das sind die coolen Kids, das sind auch die, die zu spät auf der…das sind die, die zu spät auf der Party ankommen. Und das hab ich nämlich,…",
"Das wär so ein Ziel von mir.",
"Das war…Ach, die Leute hören… die Leute sehen uns ja nicht! Das war Florentin’s Will’s… äh… Florentin Will’s Imitation einer Grille.",
"Der selbst… Leute mit se… Sonnenbrille wirken selbstbewusst.",
"Du bist der Schlechte…",
"Du kannst die Augen zu machen und…äh…qua…dafür gibt’s ja auch Hunde! Hunde führen dich!",
"Du kommst aus München, ne?",
"Es fängt schon wieder so an. Ich… ich bin nicht sympathisch.",
"Es ist eigentli… Ha ha ha! Es ist eigentlich ziemlich geil, dass man… äh… Sachen auf die Straße werfen kann, die explodieren. Objektiv…",
"Find ich gut. Das wär gut. Das wär…das wär das Richtige. Unten wäre was zu essen für’s Pferd und Pferde…Pferd…Pferd…Pferdesticker…",
"Findest du, dass Oscar wirklich so ‘ne… so ‘ne objektive Sache ist?",
"Genau.",
"Glaubst du also, dass die meisten Leute Silvester Scheiße finden?",
"Ha Ha Ha Haa!",
"Ha Ha Ha Haa!",
"Hä? Nein.",
"Hör auf, mich da r… mit ins Boot zu holen! … Also ich find mich…",
"Ich auch nicht!",
"Ich find’s gut, ich find’s super, ich versprech mich nicht…",
"Ich hab immer, ähm… Ich hab immer die, äh, Böller in der Mitte durchgebrochen, auch… Ich find das wirklich … echt scheiße von dir, dass du immer, wenn ich anfange, irgendwas zu erzählen, direkt…",
"Ich hab jedenfalls immer, angefangen, die, ähm… die Böller in der Mitte durchzubrechen, …",
"Ich hab nur Angst, dass wir Leute dann nicht mit ins Boot ziehen grad. Wir…wir sind nämlich dann…Inselkinder.",
"Ich kann da jetzt nicht drauf antworten. Wir…",
"Ich komm aus…äh… Kamen. Das Kamener Kreuz sagt vielen was…",
"Ich mag Silvester…Ich mag Silvester nicht.",
"Ich sag Ferd. Wie sagst du, Pferd?",
"Ich seh mit der Brille besser aus, meinst du?",
"Ich werde grad in ‘ner Gruppe angesprochen, und in WhatsApp-Gruppen angesprochen zu werden ist für mich immer so ‘n Riesending, weil, es fällt mir erst so Monate danach auf und,… man…man kann nicht mehr antworten, …",
"Ich… ich überbrücke kurz. Wir haben ja ‘nen Kommentar bekommen…",
"Ist das… das ist alles, was ich aus deiner Rede grade…",
"Ist ja gut, aber sagen wir mal, wenn man in den DM will…",
"Ja, das war meine erste Frage an Florentin Will.",
"Ja, genau.",
"Jetzt mal… Wir haben gelesen, ... nehmen wir schon auf eigentlich? Muss ich jetzt erklären, was ich sage? Muss ich die Leute mit ins Boot nehmen?",
"Klar!",
"Mein größter…",
"Meine Stimme is n‘ Bisschen belegt heute…Aber jetzt nicht mehr!",
"Meinst du, UV-Strahlung…",
"Na also!",
"Nee, die … Nein, die werden mich ja nicht kennen. Auch in der Welt würden die mich nicht kennen. Das wär aber auch gar nicht schlimm.",
"Nee, ich glaub, vor dir wird eher noch Nora Tschirner ‘n Oscar bekommen.",
"Nee, nee. Das wär zu einfach. Und ich find…",
"Nehmen wir schon auf eigentlich?",
"Nein, das war meine Imitation einer Grille. Äh…Das…Das stimmt wirklich? Du willst ‘nen Oscar gewinnen?",
"Nein…",
"Nö. Es ist nicht schlecht. [Pause] Eigentlich ist es ziemlich geil.",
"Nora Tschirner zum Beispiel… Nora Tschirner find ich…",
"O Gott.",
"Okay, Entschuldigung, Entschuldigung.",
"Ouuh…",
"Pferd sag ich.",
"Populismus.",
"Sonnenhunde. Die sogenannten Sonnenhunde.",
"Spaß beiseite, wir haben gelesen, da hat jemand [lacht auf] keinen Gag gemacht und hat dann geschrieben Aber jetzt Spaß beiseite und hat dann was Ernstes geschrieben,…",
"Und dass ich so… dass…dass meine Figur – die ist nicht perfekt – ein Schönheitsideal …",
"Und es ist eigentlich…eigentlich ist es auch gemeingefährlich, muss man sagen.",
"Und ich schieb gleich die zweite Frage hinterher, weil mich das… die Antwort gar nicht interessiert hat.",
"Und zwar…",
"Wenn de… wenn ich den seh, wie er seine Sonnenbrille aufsetzt, dann glaub ich, dass er sehr zufrieden mit sich selber ist. Sonnenbrillen sind so’n Ding … Ha ha ha! die Leute… aus…",
"Wieso denn nicht?",
"Wir sollten vielleicht mal aufnehmen.",
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]